---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
df<-read.csv("activity.csv")
df[,"steps"]<-as.numeric(df$steps)
df[,"date"]<-as.Date(df$date)
time<-strptime(paste(df$date, formatC(df$interval, flag="0", width=4)), "%Y-%m-%d %H%M")
```



## What is mean total number of steps taken per day?
```{r}
library(data.table)
df.dt<-data.table(df)
df.dt[,sum:=sum(steps, na.rm=TRUE), by=date]
mean(df.dt$sum)
median(df.dt$sum)
# charting
ds<-df.dt[,sum(steps, na.rm=TRUE), by=date]
plot(ds$date, ds$V1, type="h", xlab="Date", ylab="Steps")
m=mean(ds$V1)
md=median(ds$V1)
abline(h=m, col="green")
abline(h=md, col="blue")
legend("topleft", legend=c("mean", "median"), col=c("green", "blue"), lty=1)
#text(ds$date[10], y=m, round(m, digits=0))
```



## What is the average daily activity pattern?
```{r}
dm<-df.dt[,mean(steps, na.rm=TRUE), by=interval]
setkey(dm, interval)
plot(type="l", dm, ylab="Steps", xlab="Interval")
maxSteps<-max(dm$V1)
maxInterval<-dm$interval[dm$V1==maxSteps]
maxInterval
points(y=maxSteps, x=maxInterval, col="red")
text(y=maxSteps, x=maxInterval, maxInterval, pos=4)
```



## Imputing missing values
```{r}
nas<-is.na(df$steps)
sum(nas)
# use mean for the interval
stepsImputed<-df$steps
stepsImputed[is.na(stepsImputed)]<-0
stepsImputed<-stepsImputed+dm[interval==df$interval]$V1*nas
# create new dataset
df2=df
df2$steps<-stepsImputed
library(data.table)
df.dt2<-data.table(df2)
df.dt2[,sum:=sum(steps, na.rm=TRUE), by=date]
# charting
ds2<-df.dt2[,sum(steps), by=date]
plot(ds2$date, ds2$V1, type="h", xlab="Date", ylab="Steps")
m2=mean(ds2$V1)
md2=median(ds2$V1)
abline(h=m, col="green")
abline(h=m2, col="cyan")
legend("topleft", legend=c("mean", "previous mean"), col=c("cyan", "green"), lty=1)
# for each interval, the mean value does not change after imputing, when mean value for that interval is used
sum(dm$steps)
mean(df.dt2$sum)
median(df.dt2$sum)
```



## Are there differences in activity patterns between weekdays and weekends?
```{r}
df.dt2[,wf:=as.factor(ifelse(weekdays(df.dt2$date) %in% c("Saturday", "Sunday"), "weekend", "weekday"))]
dm3<-df.dt2[,mean(steps, na.rm=TRUE), by=c("interval", "wf")]
library(lattice)
xyplot(type="l", data=dm3, V1 ~ interval | wf, layout=c(1,2), ylab="Steps", xlab="Interval")
```

